workflows:
  flutter-app:
    name: Flutter Build
    environment:
      flutter: stable
    scripts:
      - name: Move to project folder and get packages
        script: |
          cd app   # اسم المجلد الذي يحتوي على pubspec.yaml
          flutter pub get
      - name: Build APK
        script: |
          cd app
          flutter build apk --release
    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
